### ISSUE TITLE
Non-column fields should always be nullable

### ISSUE THREAD

**Issue by jshah4517** [supportpal/api-client-php#130]
Model attributes that are not directly stored in column fields, such as JSON encoded arrays, should be nullable as the data may or may not be there or the format may change without needing to change the database.

A removal of an email template from the department model in an upcoming SupportPal version brought light of this issue.

**Comment by bytestream** [comment]
Following discussion it was agreed:
* `ChannelSettings` should extend the Settings model 

So I think this is the refined scope of this issue.

**Comment by jshah4517** [comment]
@bytestream test

**Comment by jshah4517** [comment]
another comment

**Comment by jshah4517** [comment]
test again

**Comment by jshah4517** [comment]
This is no longer an issue once version 2.0.0 is released.
