### ISSUE TITLE
UserCustomFieldTranslation model description should be optional

### ISSUE THREAD

**Issue by jshah4517** [supportpal/api-client-php#138]
If you translate a user custom field without a description, you will see this error in the WHMCS integration. The description is not required in translations.

```
SupportPal\WhmcsIntegration\Vendor\Symfony\Component\Serializer\Exception\NotNormalizableValueException: The type of the "description" attribute for class "SupportPal\WhmcsIntegration\Vendor\SupportPal\ApiClient\Model\User\UserCustomFieldTranslation" must be one of "string" ("null" given). in /path/public_html/modules/support/supportpal/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:416
```

**Comment by bytestream** [comment]
All the custom field translation models need the description property changing to `string|null` and associated getters / setters changing. From a glance, most other translation models are OK.
