### ISSUE TITLE
Missing operator endpoint

### ISSUE THREAD

**Issue by ju5t** [supportpal/api-client-php#159]
First of all, thanks for this :)

There is an operator endpoint missing. I know how to build a request and run it either way, but it's a bit messy. And should any of the endpoints change, for whatever reason, it's always better to use the php-client.

Is this something you're considering?

**Comment by bytestream** [comment]
@ju5t which end point are you referring to? The client doesn't currently implement all available end points. The goal would be to implement them but at the moment it's not something we're prioritizing. We'll accept a PR though.
