### ISSUE TITLE
Upgrade kevinrob/guzzle-cache-middleware

### ISSUE THREAD

**Issue by ju5t** [supportpal/api-client-php#160]
Could we update the following dependencies:

- kevinrob/guzzle-cache-middleware 4.0.0? This resolves some return type issues in previous versions. They did drop PHP 7.2 but to be fair, you guys should too.
- phpstan to 1.4.x
- Support for PHP 8.1

It shouldn't be too painful to upgrade. I ran a quick test on my machine and apart from some deprecations and two errors during tests, it all worked. I have no clue how to solve the failed tests myself.

@bytestream I can PR a failing setup if you like?

**Comment by bytestream** [comment]
Sorry I missed this @ju5t 

>  They did drop PHP 7.2

They only dropped versions prior to 7.2. PHP 7.2.0 is the required minimum https://github.com/Kevinrob/guzzle-cache-middleware/blob/22d79bb234861469e0c1d6b9541eb6d8e97ecd72/composer.json#L16

>  I can PR a failing setup if you like?

Sure, if you could send a PR but maintain PHP 7.2 support then we can help with the failing tests

**Comment by ju5t** [comment]
I've opened the PR.

**Comment by ju5t** [comment]
Awesome, thanks for the quick release!
