### ISSUE TITLE
The annotation "@Symfony\Component\Serializer\Annotation\SerializedName" is missing

### ISSUE THREAD

**Issue by tomasvts** [supportpal/api-client-php#168]
Hey there, thanks for the library.         

I got a very specific issue that I cannot pinpoint where the problem is. I'm stuck.       
I have this method which gives me the brands. All is good when testing with phpunit. It gets me the brands. 
```    private function getBrands(): array
    {
        /** @var Brand[] $brands */
        $brands = $this->api->getCoreApi()->getBrands([
            'enabled' => true,
        ])->getModels();
        return $brands;
    }
```

But when I'm manual testing/browser testing I got this error. 
```[Semantical Error] The annotation "@Symfony\Component\Serializer\Annotation\SerializedName" in property SupportPal\ApiClient\Model\Core\Brand::$operatorTemplate was never imported. Did you maybe forget to add a "use" statement for this annotation?```

I look up the Brand.php class, and It has the use statement:
![image](https://user-images.githubusercontent.com/4351937/180268619-90af5211-4d4e-464c-a64c-03d0c569d71f.png)
    
I really don't know what is going on.     
I don't know how Symfony annotations work, so I can't diagnose what's happening.

----
Im using yii2 framework.   
PHP 7.4.

**Comment by bytestream** [comment]
@tomasvts are you able to provide a simple reproducer?

**Comment by tomasvts** [comment]
I solved it adding this line 
```        
assert(class_exists(SerializedName::class));
```

It seems there's something in my project that is unregistering the annotation autoloaders
