### ISSUE TITLE
Symfony 6.3/6.4 support

### ISSUE THREAD

**Issue by ju5t** [supportpal/api-client-php#178]
Hi there @bytestream, since Symfony 6.3 we're seeing the following warnings:

```
Since symfony/serializer 6.3: "SupportPal\ApiClient\Normalizer\ModelNormalizer" should implement 
"DenormalizerInterface::getSupportedTypes(?string $format): array"
```

I am not entirely sure what this implementation should look like and it may be changed in Symfony 6.4.

**Comment by bytestream** [comment]
We could pin our version to <6.3 or <6.4 due to the interface changes. Would that be OK?

**Comment by ju5t** [comment]
That may be a problem for us. Are the necessary changes breaking changes?

If so, would it be possible to keep 1.x on Symfony 6.2 and simultaneously release 2.x with >6.3?

**Comment by Gaitholabi** [comment]
@bytestream looking at the actual Symfony code, it looks like a _soft_ interface deprecation. I had previously imagined a change in the interface in 6.4, which luckily isn't the case. I think just adding `getSupportedTypes` would do the trick.  Later with Symfony 7.x we'll have to pin later versions.
