### ISSUE TITLE
Upgrade dependency versions

### ISSUE THREAD

**Issue by pstoute** [supportpal/api-client-php#182]
We were going to use the API client in our Laravel application which has higher dependency version requirements than the versions that you're locked using. 

doctrine/lexer (2.1.1 vs 3.0.1)
psr/http-message (1.1 vs 2.0)
symfony/yaml (6.4.7 vs 7.0.7)

I haven't looked into if the older versions have any vulnerabilities, but it would be awesome if the PHP client could be updated to use the newer versions.

**Comment by jshah4517** [comment]
Closing as this has been completed, new tag (with breaking changes) will be released soon.

**Comment by itsmejoshua** [comment]
I dont think you should close this until the release tag is actually out...

**Comment by pstoute** [comment]
I just attempted to install this in a fresh Laravel app v11 and am getting an error related to the psr/http-message version requirement. See screenshot.

`./composer.json has been updated
Running composer update supportpal/api-client-php
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - supportpal/api-client-php[v1.0.0, ..., v1.7.1, v2.0.0] require psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires supportpal/api-client-php * -> satisfiable by supportpal/api-client-php[v1.0.0, ..., v1.7.1, v2.0.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require supportpal/api-client-php:*" to figure out if any version is installable, or "composer require supportpal/api-client-php:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
`

<img width="1186" alt="Screenshot 2024-07-08 at 10 54 22 AM" src="https://github.com/supportpal/api-client-php/assets/669308/e387fec8-8934-4281-a946-c6fcdcf76126">

**Comment by jshah4517** [comment]
@pstoute we have updated the dependency that was causing the trouble, please give it another go?

**Comment by pstoute** [comment]
Thanks that resolved the first dependency. Looks like doctrine/cache is another one that needs to be updated too. 
<img width="1185" alt="Screenshot 2024-07-09 at 5 24 58 AM" src="https://github.com/supportpal/api-client-php/assets/669308/309cda3a-f39a-486d-a384-0b9092b6631d">

**Comment by pstoute** [comment]
I just ran a fresh laravel project and as long as I install the supportpal package before I install Filament, it works. If I do it after then I have to downgrade doctrine/cache. 

I'll keep running some tests and see if we can figure out exactly which package was causing a conflict, but at this moment, I imagine this could be a closed issue since vanilla laravel and jetstream +  livewire have no conflicts on their own now that you have fixed the http-message version requirements. 

Thanks!
