### ISSUE TITLE
Add optional default options to Guzzle

### ISSUE THREAD

**Issue by Gaitholabi** [supportpal/api-client-php#43]
Add the ability to pass default options to Guzzle, such as disable SSL certificate check, number of retries.etc

**Comment by bytestream** [comment]
How did you envisage doing this? I don't really want to add another `__constructor` argument, if anything I'd rather reduce the current list.

Not sure if this is feasible but I think it would be ideal if `default_parameters` and `default_body` were turned into `guzzle_options`:
* `default_parameters` -> https://docs.guzzlephp.org/en/stable/request-options.html#query
* `default_body` -> https://docs.guzzlephp.org/en/stable/request-options.html#body

I'm also wondering why we're not using the below options at the moment?
* `base_uri` (https://docs.guzzlephp.org/en/stable/request-options.html)
* https://docs.guzzlephp.org/en/stable/request-options.html#auth

**Comment by Gaitholabi** [comment]
I wanted to add a new object with builder pattern for this. an interface with getters / setters for the default options ( all related to PHP options).

These default parameters has to be merged with the other parameters somehow, we're doing that in: https://github.com/supportpal/api-client-php/blob/master/src/Factory/RequestFactory.php

As for baseUri and the given options, the reason we're not using this is because effectively we're using PSR client interface, https://www.php-fig.org/psr/psr-18/

We're just using Guzzle to implement it, thus, all the information of the request should be encapsulated in the PSR-7 Request, not Guzzle.

This way, if someday something better than Guzzle emerges, swapping is extremely easy.
