### ISSUE TITLE
getTag() clashes with ticket_tag

### ISSUE THREAD

**Issue by bytestream** [supportpal/api-client-php#50]
Some method names will clash if we add more end points to the library.

For example:
* https://api.supportpal.com/api.html#self-service-tag-get-1
* https://api.supportpal.com/api.html#ticket-tag-get-1

I guess it would make more sense to call it `getSelfserviceTag()` ?

Does this sound OK @Gaitholabi ?

**Comment by Gaitholabi** [comment]
Sure, this will make it more scaleable on the long term
