### ISSUE TITLE
All POST Apis should have their relevant models

### ISSUE THREAD

**Issue by Gaitholabi** [supportpal/api-client-php#56]
When using POST Apis, the current models serialization to does not exactly match the keys and values required by the endpoints.  separate models should be created for POST requests, and all previous POST apis should be refactored to use new models.

**Comment by bytestream** [comment]
Please can you describe an example that is affected by this? I don't understand.

**Comment by Gaitholabi** [comment]
Take for example: https://api.supportpal.com/api.html#ticket-message-post
In the Message object, we have a list of attachments.  however, in the POST, there's an array that contains only two fields. 
In other cases, like: https://api.supportpal.com/api.html#ticket-ticket-post, the name of the field is `tag` where as the GET endpoint return `tags`

A simple solution would have been to simply remove subobject and replace with 'id', but this won't work with cases like attachments
